import { app, BrowserWindow, Menu, session, ipcMain } from "electron";
import { HIDController } from "./components/controller/hid-controller";
import { serialController } from "./components/controller/serial-controller";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// IPC handler to allow renderer to call serial sendShift
ipcMain.handle('serial-sendShift', async (_event, value: number) => {
  try {
    if (serialController) {
      serialController.sendShift(Number(value) || 0);
      return { ok: true };
    }
    return { ok: false, error: 'no-serial-controller' };
  } catch (err) {
    console.error('sendShift error', err);
    return { ok: false, error: String(err) };
  }
});

const createWindow = (): void => {
  // Create the browser window.
  Menu.setApplicationMenu(null);
  const mainWindow = new BrowserWindow({
    height: 1920,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  // keep the window at the configured size and position
  mainWindow.maximize();

  // Open the DevTools in a detached (floating) window.
  // mainWindow.webContents.openDevTools({ mode: 'detach' });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
let controller: HIDController | null = null;

function initController(): void {
  try {
    controller = new HIDController();
    controller.on("data", (payload) => {
        // broadcast to renderer processes
        BrowserWindow.getAllWindows().forEach((w) =>
          w.webContents.send("controller-data", payload),
        );
    });
    controller.on("connected", (info) =>
      console.log("Controller connected:", info),
    );
    controller.on("error", (err) => console.error("Controller error:", err));
    controller
      .discoverAndConnect()
      .catch((err) => console.error("Controller connect failed:", err));
  } catch (err) {
    console.error("initController failed:", err);
  }
}

app.on("ready", () => {
  createWindow();
  initController();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
